name: awesome_quotes
description: Utilities for getting (local) random quotes.
version: 0.0.1
repository: https://github.com/palves-ulht/awesome_quotes

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
